#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/bootstrap.php';

$config = require __DIR__ . '/console/config/main.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
